[project]
name = "fast-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastai>=2.8.1",
    "ipywidgets>=8.1.7",
    "jupyter>=1.1.1",
]
